using System.Reflection;
using BankSharp.Validation;

#if NET10_0_OR_GREATER
using Microsoft.AspNetCore.OpenApi;
using Microsoft.OpenApi;
using System.Text.Json.Nodes;
#elif NET9_0
using Microsoft.AspNetCore.OpenApi;
using Microsoft.OpenApi.Models;
using Microsoft.OpenApi.Any;
#elif NET8_0
using Swashbuckle.AspNetCore.SwaggerGen;
using Microsoft.OpenApi.Models;
using Microsoft.OpenApi.Any;
#endif

namespace BankSharp.OpenApi;

#if NET9_0_OR_GREATER
/// <summary>
/// Enriches OpenAPI document schemas by detecting properties decorated with <see cref="IbanAttribute"/> 
/// or strongly-typed <see cref="Iban"/> properties, applying standard ISO 13616 IBAN metadata, 
/// length constraints, descriptions, and sample values.
/// </summary>
/// <remarks>
/// Targets the built-in OpenAPI transformer pipeline in ASP.NET Core (.NET 9 / .NET 10+).
/// </remarks>
public sealed class IbanSchemaTransformer : IOpenApiSchemaTransformer
{
    private const string SampleIban = "IR660170000000123456789012";

    /// <summary>
    /// Transforms the OpenAPI schema for properties matching IBAN types or validation attributes.
    /// </summary>
    /// <param name="schema">The OpenAPI schema being generated for the property or type.</param>
    /// <param name="context">The contextual metadata regarding the type and JSON property.</param>
    /// <param name="cancellationToken">A token to observe while waiting for the task to complete.</param>
    /// <returns>A completed <see cref="Task"/> representing the asynchronous operation.</returns>
    public Task TransformAsync(OpenApiSchema schema, OpenApiSchemaTransformerContext context, CancellationToken cancellationToken)
    {
        // 1. Determine target property type or root type
        var propertyType = context.JsonPropertyInfo?.PropertyType ?? context.JsonTypeInfo.Type;
        var isIbanType = propertyType == typeof(Iban) || propertyType == typeof(Iban?);

        // 2. Check for [Iban] attribute on the property provider
        var attributeProvider = context.JsonPropertyInfo?.AttributeProvider;
        var hasIbanAttribute = attributeProvider?.GetCustomAttributes(typeof(IbanAttribute), inherit: true).Length > 0;

        if (hasIbanAttribute || isIbanType)
        {
            ApplyIbanMetadata(schema);
        }

        return Task.CompletedTask;
    }

    /// <summary>
    /// Applies IBAN-specific constraints and metadata (format, lengths, description, sample example) to the schema.
    /// </summary>
    /// <param name="schema">The schema instance to modify.</param>
    private static void ApplyIbanMetadata(OpenApiSchema schema)
    {
        schema.Format = "iban";
        schema.MinLength = 15;
        schema.MaxLength = 34;
        schema.Description = "International Bank Account Number (ISO 13616 standard).";

#if NET10_0_OR_GREATER
        // In .NET 10 with Microsoft.OpenApi 2.x, types use the JsonSchemaType enum and examples use JsonNode/JsonValue
        schema.Type = JsonSchemaType.String;
        schema.Example = JsonValue.Create(SampleIban);
#else
        // In .NET 9 with Microsoft.OpenApi 1.6.x object model
        schema.Type = "string";
        schema.Example = new OpenApiString(SampleIban);
#endif
    }
}
#else
/// <summary>
/// Enriches Swashbuckle Swagger/OpenAPI schemas by detecting properties decorated with <see cref="IbanAttribute"/> 
/// or strongly-typed <see cref="Iban"/> properties, applying standard ISO 13616 IBAN metadata, 
/// length constraints, descriptions, and sample values.
/// </summary>
/// <remarks>
/// Targets Swashbuckle.AspNetCore schema generation pipeline for .NET 8.
/// </remarks>
public sealed class IbanSchemaTransformer : ISchemaFilter
{
    private const string SampleIban = "IR660170000000123456789012";

    /// <summary>
    /// Applies IBAN schema customizations to properties or types matching IBAN signatures.
    /// </summary>
    /// <param name="schema">The OpenAPI schema generated by Swashbuckle.</param>
    /// <param name="context">The schema filter context providing member and type details.</param>
    public void Apply(OpenApiSchema schema, SchemaFilterContext context)
    {
        var targetType = context.Type;
        var memberInfo = context.MemberInfo;

        var hasIbanAttribute = memberInfo?.GetCustomAttribute<IbanAttribute>() != null;
        var isIbanType = targetType == typeof(Iban) || targetType == typeof(Iban?);

        if (hasIbanAttribute || isIbanType)
        {
            schema.Format = "iban";
            schema.MinLength = 15;
            schema.MaxLength = 34;
            schema.Description = "International Bank Account Number (ISO 13616 standard).";
            schema.Type = "string";
            schema.Example = new OpenApiString(SampleIban);
        }
    }
}
#endif
